# Generated by Django 3.1.6 on 2021-03-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210303_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengesummary',
            name='asked_count',
            field=models.IntegerField(default=0),
        ),
    ]
